import { KeyValue } from '@angular/common';

export const INDIAN_STATE_LIST: KeyValue<string, string>[] =
    [
        { key: 'KL', value: 'Kerala' },
        { key: 'AN', value: 'Andaman and Nicobar Islands' },
        { key: 'AP', value: 'Andhra Pradesh' },
        { key: 'AR', value: 'Arunachal Pradesh' },
        { key: 'AS', value: 'Assam' },
        { key: 'BR', value: 'Bihar' },
        { key: 'CG', value: 'Chandigarh' },
        { key: 'CH', value: 'Chhattisgarh' },
        { key: 'DH', value: 'Dadra and Nagar Haveli' },
        { key: 'DD', value: 'Daman and Diu' },
        { key: 'DL', value: 'Delhi' },
        { key: 'GA', value: 'Goa' },
        { key: 'GJ', value: 'Gujarat' },
        { key: 'HR', value: 'Haryana' },
        { key: 'HP', value: 'Himachal Pradesh' },
        { key: 'JK', value: 'Jammu and Kashmir' },
        { key: 'JH', value: 'Jharkhand' },
        { key: 'KA', value: 'Karnataka' },
        { key: 'LD', value: 'Lakshadweep' },
        { key: 'MP', value: 'Madhya Pradesh' },
        { key: 'MH', value: 'Maharashtra' },
        { key: 'MN', value: 'Manipur' },
        { key: 'ML', value: 'Meghalaya' },
        { key: 'MZ', value: 'Mizoram' },
        { key: 'NL', value: 'Nagaland' },
        { key: 'OR', value: 'Odisha' },
        { key: 'PY', value: 'Puducherry' },
        { key: 'PB', value: 'Punjab' },
        { key: 'RJ', value: 'Rajasthan' },
        { key: 'SK', value: 'Sikkim' },
        { key: 'TN', value: 'Tamil Nadu' },
        { key: 'TS', value: 'Telangana' },
        { key: 'TR', value: 'Tripura' },
        { key: 'UK', value: 'Uttarakhand' },
        { key: 'UP', value: 'Uttar Pradesh' },
        { key: 'WB', value: 'West Bengal' }
    ];
